[package]
name = "extract_traffic_infrom"
version = "0.1.0"
edition = "2021"

[dependencies]
dbase = "0.5.0"
shapefile = "0.6"   # or 최신 버전 확인
zip = "2.2.2" #
csv = "1.1"# or 최신 버전 확인
chrono = "0.4"# or 최신 버전 확인